"""Add ExpiryTable

Revision ID: 385b658b3c88
Revises: 7841350fbe23
Create Date: 2025-05-20 23:00:23.131595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385b658b3c88'
down_revision = '7841350fbe23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expiry_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('expiry_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    expiry_table = sa.table(
        'expiry_table',
        sa.column('name', sa.String(length=128)),
        sa.column('expiry_days', sa.Integer()),
    )

    op.bulk_insert(expiry_table, [
        {'name': 'Apple', 'expiry_days': 10},
        {'name': 'Banana', 'expiry_days': 3},
        {'name': 'Bell Pepper', 'expiry_days': 10},
        {'name': 'Cabbage', 'expiry_days': 60},
        {'name': 'Carrot', 'expiry_days': 25},
        {'name': 'Cauliflower', 'expiry_days': 10},
        {'name': 'Cucumber', 'expiry_days': 10},
        {'name': 'Eggplant', 'expiry_days': 10},
        {'name': 'Grape', 'expiry_days': 10},
        {'name': 'Kiwi', 'expiry_days': 10},
        {'name': 'Lemon', 'expiry_days': 10},
        {'name': 'Lettuce', 'expiry_days': 10},
        {'name': 'Mango', 'expiry_days': 10},
        {'name': 'Onion', 'expiry_days': 10},
        {'name': 'Orange', 'expiry_days': 7},
        {'name': 'Papers', 'expiry_days': 10},
        {'name': 'Peach', 'expiry_days': 10},
        {'name': 'Pear', 'expiry_days': 10},
        {'name': 'Potato', 'expiry_days': 10},
        {'name': 'Strawberry', 'expiry_days': 10},
        {'name': 'Test', 'expiry_days': 10},
        {'name': 'Tomato', 'expiry_days': 10},
        {'name': 'Training', 'expiry_days': 10},
        {'name': 'Validation', 'expiry_days': 10},
        {'name': 'fruits-360_original-size', 'expiry_days': 10},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expiry_table')
    # ### end Alembic commands ###
